#!/bin/bash
#===============================================================================
# Copyright (c) 2014-2015 Wind River Systems, Inc.
# The right to copy, distribute, modify, or otherwise
# make use of this software may be licensed only pursuant
# to the terms of an applicable Wind River license agreement.
#
#===============================================================================
case "$1" in
	start)
		/usr/sbin/watchdog -f -c %etcdir%/iot-watchdog.conf
		exit 0
		;;
	stop)
		/usr/bin/pkill -x watchdog
		exit 0
		;;
esac

